=== bassamelobeid/flutter-deriv-api/config/v3/new_account_maltainvest/send.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title":"Create maltainvest account Send",
  "description": "This call opens a new real-money account with the 'maltainvest' Landing Company. Note: you must be authenticated to Binary (Europe) Ltd or virtual-money account to call this function.",
  "properties": {
    "new_account_maltainvest": {
      "type": "integer",
      "description": "Must be 1",
      "pattern": "^1$",
      "required": "1"
    },
    "salutation" : {
      "enum": ["Mr", "Mrs", "Ms", "Miss"],
      "description": "Accept any value in enum list."
    },
    "first_name": {
      "type": "string",
      "pattern": "^[\\p{L}\\s'.-]{2,30}$",
      "description": "Within 2-30 characters, use only letters, spaces, hyphens, full-stops or apostrophes."
    },
    "last_name": {
      "type": "string",
      "pattern": "^[\\p{L}\\s'.-]{2,30}$",
      "description": "Within 2-30 characters, use only letters, spaces, hyphens, full-stops or apostrophes."
    },
    "date_of_birth" : {
      "type": "string",
      "pattern": "^\\d{4}-\\d\\d?-\\d\\d?$",
      "description": "Date of birth format: yyyy-mm-dd."
    },
    "residence" : {
      "type" : "string",
      "pattern": "^[a-z]{2}$",
      "description": "2-letter country code, possible value receive from residence_list call."
    },
    "address_line_1": {
      "type" : "string",
      "minLength": 1,
      "maxLength": 70,
      "description": "Within 70 characters."
    },
    "address_line_2": {
      "type" : "string",
      "maxLength": 70,
      "description": "Optional field, within 70 characters."
    },
    "address_city": {
      "type" : "string",
      "minLength": 1,
      "maxLength": 35,
      "description": "Within 35 characters"
    },
    "address_state": {
      "type" : "string",
      "maxLength": 35,
      "description": "Optional field, possible value receive from states_list call."
    },
    "address_postcode": {
      "type" : "string",
      "pattern": "^[^+]{0,20}$",
      "description": "Optional field, within 20 characters and may not contain '+'."
    },
    "phone": {
      "type" : "string",
      "pattern": "^\\+?[0-9\\s]{6,35}$",
      "description": "Within 6-35 digits, allowing '+' in front, numbers or space."
    },
    "secret_question": {
      "enum": [ "Mother's maiden name", "Name of your pet", "Name of first love", "Memorable town/city", "Memorable date", "Favourite dish", "Brand of first car", "Favourite artist" ],
      "description": "Accept any value in enum list."
    },
    "secret_answer": {
      "type": "string",
      "minLength": 4,
      "maxLength": 50,
      "description": "Answer to secret question, within 4-50 characters."
    },
    "affiliate_token": {
      "type": "string",
      "pattern": "^[\\w-]{0,32}$",
      "description": "Affiliate token, within 32 characters."
    },
    "forex_trading_experience": {
      "enum": [ "0-1 year", "1-2 years", "Over 3 years" ],
      "description": "Forex trading experience",
      "required": 1
    },
    "forex_trading_frequency": {
      "enum": [ "0-5 transactions in the past 12 months", "6-10 transactions in the past 12 months", "40 transactions or more in the past 12 months" ],
      "description": "Forex trading frequency",
      "required": 1
    },
    "indices_trading_experience": {
      "enum": [ "0-1 year", "1-2 years", "Over 3 years" ],
      "description": "Indices trading experience",
      "required": 1
    },
    "indices_trading_frequency": {
      "enum": [ "0-5 transactions in the past 12 months", "6-10 transactions in the past 12 months", "40 transactions or more in the past 12 months" ],
      "description": "Indices trading frequency",
      "required": 1
    },
    "commodities_trading_experience": {
      "enum": [ "0-1 year", "1-2 years", "Over 3 years" ],
      "description": "Commodities trading experience",
      "required": 1
    },
    "commodities_trading_frequency": {
      "enum": [ "0-5 transactions in the past 12 months", "6-10 transactions in the past 12 months", "40 transactions or more in the past 12 months" ],
      "description": "Commodities trading frequency",
      "required": 1
    },
    "stocks_trading_experience": {
      "enum": [ "0-1 year", "1-2 years", "Over 3 years" ],
      "description": "Stocks trading experience",
      "required": 1
    },
    "stocks_trading_frequency": {
      "enum": [ "0-5 transactions in the past 12 months", "6-10 transactions in the past 12 months", "40 transactions or more in the past 12 months" ],
      "description": "Stocks trading frequency",
      "required": 1
    },
    "other_derivatives_trading_experience": {
      "enum": [ "0-1 year", "1-2 years", "Over 3 years" ],
      "description": "Binary options or other financial derivatives trading experience",
      "required": 1
    },
    "other_derivatives_trading_frequency": {
      "enum": [ "0-5 transactions in the past 12 months", "6-10 transactions in the past 12 months", "40 transactions or more in the past 12 months" ],
      "description": "Binary options or other financial derivatives trading frequency",
      "required": 1
    },
    "other_instruments_trading_experience": {
      "enum": [ "0-1 year", "1-2 years", "Over 3 years" ],
      "description": "Other financial instruments trading experience",
      "required": 1
    },
    "other_instruments_trading_frequency": {
      "enum": [ "0-5 transactions in the past 12 months", "6-10 transactions in the past 12 months", "40 transactions or more in the past 12 months" ],
      "description": "Other financial instruments trading frequency",
      "required": 1
    },
    "employment_industry": {
      "enum": [ "Construction", "Education", "Finance", "Health", "Tourism", "Other" ],
      "description": "Industry of Employment",
      "required": 1
    },
    "education_level": {
      "enum": [ "Primary", "Secondary", "Tertiary" ],
      "description": "Level of Education",
      "required": 1
    },
    "income_source": {
      "enum": [ "Salaried Employee", "Self-Employed", "Investments & Dividends", "Pension", "Other" ],
      "description": "Income Source",
      "required": 1
    },
    "net_income": {
      "enum": [ "Less than $25,000", "$25,000 - $50,000", "$50,001 - $100,000", "$100,001 - $500,000", "Over $500,000" ],
      "description": "Net Annual Income",
      "required": 1
    },
    "estimated_worth": {
      "enum": [ "Less than $100,000", "$100,000 - $250,000", "$250,001 - $500,000", "$500,001 - $1,000,000", "Over $1,000,000" ],
      "description": "Estimated Net Worth",
      "required": 1
    },
    "accept_risk" : {
      "type": "integer",
      "description": "Show whether client has accepted risk disclaimer, boolean value 1 or 0",
      "required": 1
    },
    "passthrough": {
      "type": "object",
      "description": "Optional field, used to pass data through the websocket, which may be retrieved via the echo_req output field."
    },
    "req_id": {
      "type": "integer",
      "description": "Optional field to map request to response"
    }
  },
  "additionalProperties": false
}

=== bassamelobeid/flutter-deriv-api/config/v3/new_account_maltainvest/test_send.json
{
  "new_account_maltainvest": 1,
  "salutation": "Mr",
  "first_name": "Captain",
  "last_name": "Hook",
  "date_of_birth": "1980-01-31",
  "residence": "be",
  "address_line_1": "20 Broadway Av",
  "address_line_2": "East Melbourne VIC",
  "address_city": "Melbourne",
  "address_state": "Victoria",
  "address_postcode": "3002",
  "phone": "+6123456789",
  "secret_question": "Mother's maiden name",
  "secret_answer": "Jones",
  "forex_trading_experience": "Over 3 years",
  "forex_trading_frequency": "0-5 transactions in the past 12 months",
  "indices_trading_experience": "1-2 years",
  "indices_trading_frequency": "40 transactions or more in the past 12 months",
  "commodities_trading_experience": "1-2 years",
  "commodities_trading_frequency": "0-5 transactions in the past 12 months",
  "stocks_trading_experience": "1-2 years",
  "stocks_trading_frequency": "0-5 transactions in the past 12 months",
  "other_derivatives_trading_experience": "Over 3 years",
  "other_derivatives_trading_frequency": "0-5 transactions in the past 12 months",
  "other_instruments_trading_experience": "Over 3 years",
  "other_instruments_trading_frequency": "6-10 transactions in the past 12 months",
  "employment_industry": "Finance",
  "education_level": "Secondary",
  "income_source": "Self-Employed",
  "net_income": "$25,000 - $50,000",
  "estimated_worth": "$100,000 - $250,000",
  "accept_risk": 1
}
